services:
  postgres-db:
    container_name: db-postgree
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - 5432
      #volumes:
      #- ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - funko-network

networks:
  funko-network:
    driver: bridge