services:
  postgres-db:
    container_name: db-postgree
    image: postgres:12-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - funko-network
  mongo-db:
    container_name: db_mongo
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: database
    ports:
      - 27017:27017
    volumes:
      - ./database/funkos.js:/docker-entrypoint-initdb.d/funkos.js:ro
    networks:
      - funko-network
networks:
  funko-network:
    driver: bridge